version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - '16543:80'
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - db_network

volumes:
  postgres_data:

networks:
  db_network:
